[package]
name = "spanish-numbers"
version = "0.1.1"
authors = ["Marcio Diaz <marcio.diaz@gmail.com>"]
description = "Convert integers to written Spanish number format"
keywords = ["spanish", "number", "convert", "format"]
license = "MIT"

[dependencies]
getopts = "0.2"